remote_configuration: false
no_config_watch: true
soulseek:
    #enc!
    username: ENC[AES256_GCM,data:p+j8GEpR0u0=,iv:hBPa00cz1V6MqKX9HQX9bGNLrHyXGkj9Sv1+32ex4rw=,tag:OqL4oVtMpgiKgHbWGcQ4Zg==,type:str]
    #enc!
    password: ENC[AES256_GCM,data:ECQgbl5GXCdnMg3DDa6LVKeKawAxCqydAQp+ttdmyzZ1aPd5E+2jfKCqPiMAqbq1eGU=,iv:JvZAhro6MBbEdHtIjPpSyxtQdjbq031xeSvcPH9tMpg=,tag:1jkzozB0EzOV7UWD1OBplQ==,type:str]
shares:
    directories:
        - /share
web:
    https:
        disabled: true
    authentication:
        disabled: false
        #enc!
        username: ENC[AES256_GCM,data:zZBHE5VuDpw=,iv:mP4EVEbNdLhPV4hix24pBGDvUaNRMJLHwwp+bXvsHG4=,tag:6bEQX/JG65RVRszNRK5/lg==,type:str]
        #enc!
        password: ENC[AES256_GCM,data:2v3vskJHgwMPzXdFHAKwwGfwG9JOfeUYGlBK9FDy51jjzRw3pANEJ54nNIcYgOuCfw0=,iv:uprO2aWjMBeTdQYSBOyDyBWydegIHPK/B1aFis7QHPc=,tag:iBiyokuGfDXPZ7Udw0j2qA==,type:str]
        api_keys:
            explo:
                #enc!
                key: ENC[AES256_GCM,data:SB2c6Ge99Ue1WBpPfU/Qj9yPxhnv+orsZT0FG1PiGhuXI2BTWHWViY/vqg==,iv:JSjko7aPI4gG4VF3Xzo2HUq3Fg7QTVTnaucVSJwYBhU=,tag:y9/wWqTS+c6FKujhBAnGiA==,type:str]
                cidr: 0.0.0.0/0
retention:
    search: 60
    transfers:
        download:
            # 1 day, in minutes
            succeeded: 1440
            # 2 weeks, in minutes
            errored: 20160
            cancelled: 5
integrations:
    scripts:
        auto-import:
            "on":
                - DownloadDirectoryComplete
            run:
                executable: /local/auto-import.sh
sops:
    age:
        - recipient: age14nu42yf645xewsdgq03rwytpxw4pf6elmlwz9q3yundv32h8l3xqvq7hvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UXB2RE5iU1BUckl2M3ZN
            dVRYblhBL2RwYXpEdTJKOGlwcWF4YmNtOXlrCmVlNkpSRlhtUUJMMzlZdWNyMk9G
            OUVUejQ4L2lvdVRVMFN0elVCRElkNTAKLS0tIGxOcGIxbHVpNE5JQzR5VG5FV2pD
            NHdHaStxZWc5aU1FU0Y2ZUZYQkJ1QlkKx9wVR/YFWxIcDmzpi/DLdssVqrEN8NEm
            LgEoNLQ90r3SWh+YTIp47XHuEdaS1izdbB+Vc8qh/92iqzwC9NxqWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T09:01:43Z"
    mac: ENC[AES256_GCM,data:Hva7MWBDQKSYgWwUFNj8lplcanqbDi9MpMsJmrM28ubwAKPXGXR5TT47PgM4VCrJFnrcTVeOGVOhOjmAJr84nfxmvw0VoP7dtTQisTPJ4d1RAypXh2de0MmpqW3z8OF4ZTZN54K+6SSbUQKkDoUr9KUH0CogYmISCL4tP+Uv5F0=,iv:dsWGcArFEGf3LbPp7wT87Eio9BfIe+2NnSg/HlDOOZc=,tag:FjpPy49ni/wYzwIRYfDeFA==,type:str]
    encrypted_comment_regex: enc!
    version: 3.10.2
