remote_configuration: false
soulseek:
    #enc!
    username: ENC[AES256_GCM,data:sePLf7XDdXo=,iv:Q10soFLHBhwL6MqclGdjXcEZhcuD5OyCp189aAAKjYE=,tag:Gmw3G50+bM9/hYXMSnoNmA==,type:str]
    #enc!
    password: ENC[AES256_GCM,data:sffxTVX/h5WYk1xVIC1ABwQKPuCzr4kdPk5aOc4k7Yv9cK9PUyZsLDmN1/S2MDKeQC4=,iv:pnsbhvkAcFBye6e4T2SV3z8M+v3L9jenYSK3GnQmo4E=,tag:QQZ3yAWdQ56eelt2i3nSfw==,type:str]
shares:
    directories:
        - /share
web:
    https:
        disabled: true
    authentication:
        disabled: false
        #enc!
        username: ENC[AES256_GCM,data:0P57i0GZyUQ=,iv:MCq/JebpC+aS/HbDH+5iTe8V3EfwZ8d3npzggJJmOJk=,tag:uQ8vmZMZsSv4UX+5N1XKMA==,type:str]
        #enc!
        password: ENC[AES256_GCM,data:hpX4Nts0lLC55FYYj1Im4M9Y+cwlut1EBz6cYNYWVxqowj/H77P1BRmAPQm1uTel1gA=,iv:dxA8Us4RSqEryl0Oq53sqEKABFOt6bVktBtZKmGtUZk=,tag:czphSduIJniJNHFzP02ggw==,type:str]
        api_keys:
            explo:
                #enc!
                key: ENC[AES256_GCM,data:PMNdIo+oY56jQ+rSIvDWAIOlRVN394RpnLgDDZWspuswKs1GgVfL+kxZxw==,iv:sNRVZwVToQ7PPEmogl0/nDxJE1igy6idQPMGyBKgeeI=,tag:criANtrfRzIs8yt1Q28KEQ==,type:str]
                cidr: 0.0.0.0/0
retention:
    search: 60
    transfers:
        download:
            # 1 day, in minutes
            succeeded: 1440
            # 2 weeks, in minutes
            errored: 20160
            cancelled: 5
integrations:
    scripts:
        auto-import:
            "on":
                - DownloadDirectoryComplete
            run:
                executable: /local/auto-import.sh
sops:
    age:
        - recipient: age14nu42yf645xewsdgq03rwytpxw4pf6elmlwz9q3yundv32h8l3xqvq7hvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTytmdFhHdE1xTTBVcjM4
            Q1IyZW52Q2czd1dDd3J2bEV5YVliT01aRUhzCjhGcElUelEwYWFVSGlEWDQ5VTJR
            YnNucnhJUzF1L3FOMmxPV0hPZ1V1eFkKLS0tIEk2ZXNONmtxbytwR0hxTlFDZmw1
            dkhQQ3prUEUvTTkxbnJ1citGN3g5RWcK2Ch3oKPXtDtn86zle19MQNvANAVPcFH3
            mrZRa/DhS6eUHptu2j5oHNqTQI0qjpGl/JlZ+ufAEVZnPQG5sFOa4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T13:14:23Z"
    mac: ENC[AES256_GCM,data:NI/U86t6dwgvdyLosgmlk/a96+C/6ci+5we6H5yO+0d/w8Cs09meL/B/i8rCS5DVJVF5Y9APMEstXty+W3bxWmm1RnC9jvQqQhPQPhn+sdtnN+jy6FY/SCMUG22aW6hswvEl2hpUWv7xpTHGd3tvGoTzSDtNaVZUMlsDuifg36o=,iv:MU9nbtKlr0OTPj+6uMpoGPUxbEezat7JMu3N4eOeab4=,tag:JJ0Oo2KudSWj92iuCkfjvg==,type:str]
    encrypted_comment_regex: enc!
    version: 3.10.2
