remote_configuration: false
soulseek:
    #enc!
    username: ENC[AES256_GCM,data:wyiHOVnG0YI=,iv:4/sSZrSH+NQMLDC6ybq5begpC+frXFa7itEr6EN7Cfw=,tag:ksa2IXeU2l0p5Gy9ld88Pg==,type:str]
    #enc!
    password: ENC[AES256_GCM,data:gB2CzBeg9zKjJLuUHNakAsEB7AIKQXSWJI2nu8Ofrfeky3xfpHwaX44Bm7zhaiNkDKg=,iv:iI0MTgcXq/QaIUzqY03Br6bJFjiBsQwgJoLTLNzzaSI=,tag:DZIev1vo4Wf23hJcBLfDDA==,type:str]
shares:
    directories:
        - /share
web:
    https:
        disabled: true
    authentication:
        disabled: false
        #enc!
        username: ENC[AES256_GCM,data:5M51qeKPigc=,iv:CC5JtlOhkwUcdtpqXsBCaXa30IllA+1MnCCAaknugm4=,tag:0l4cIU8HonDy9eHlhcb4aA==,type:str]
        #enc!
        password: ENC[AES256_GCM,data:aWeZ9Y6FKfng32ReiZyBs23kNBQrxE4vq/TRoS7Ml8yN6E9VMjq4XFGhVtxgIxHJxnc=,iv:lJT1nlfl8zfYS3siS+3n2fP2ZmxsdoqjImgzx6zcT+U=,tag:81kBbNcm9Ey6WClsNYeedA==,type:str]
        api_keys:
            explo:
                #enc!
                key: ENC[AES256_GCM,data:3x8xAeaivVkImFEjJI8UxOwhx7pVCjyyIceeSbhMrQYMDjEjy+Z+cpbGWw==,iv:bjoZ1UH3HAvr2h4Ph3bTDVgpPeVg7Qrwq21kj2IzUOM=,tag:ffRqx6auuglCnxVCn2dYxQ==,type:str]
                cidr: 0.0.0.0/0
retention:
    search: 60
    transfers:
        download:
            # 1 day, in minutes
            succeeded: 1440
            # 2 weeks, in minutes
            errored: 20160
            cancelled: 5
integrations:
    scripts:
        auto-import:
            "on":
                - DownloadDirectoryComplete
            run:
                executable: /local/auto-import.sh
sops:
    age:
        - recipient: age14nu42yf645xewsdgq03rwytpxw4pf6elmlwz9q3yundv32h8l3xqvq7hvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZkxjK2ZOaTR0OUsyUk9h
            aVdxeWlvQ1dGSkU3dEJCTkVKMnJ5bGJuRTBFCnZsR0FNL0NjRVRXb1hwMFhVSVZo
            bXZESWFWN2NVbG8rQnJaM3hwd3ZLTDgKLS0tIE9RdlNYZU1oYkM0ZUZFOG5QRm1E
            R3lWT3BuVHFQTGc4Ky9OWlEraWEyQTAKMofYQS6qxxoPC/Nhg2Ch2AUK4C8gRlVt
            YDjfqQjOxQA9GW0NCj7MdA2qFJXK+1y1Xgm+J48z5OpLWN3G5hQ5BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T16:30:45Z"
    mac: ENC[AES256_GCM,data:nY44TRZc6GUmye/eHC2T12a1CMYAsq3TGOTV9or9XFZ8Xru8/gF+NVSDQnmRX+5OoJZM3TwI+lMeVXmsfYf6wplmmQus5wd2Ql9XTO45wE4BrQqvLYcdKWtaKoBrxny+xXyaEPX6nOtXSpO8NkIt8qt7UAyG+/oNDJpi2yojSLs=,iv:os+d6dVixwa3e/j/qM4lhW80iIiiuddjmAwDYoNoFrk=,tag:z9f+Wk58aXiT70U4YO+RsA==,type:str]
    encrypted_comment_regex: enc!
    version: 3.10.2
