scope: patroni
name: {{ env "attr.unique.hostname" }}

restapi:
  listen: 0.0.0.0:{{ env "NOMAD_PORT_patroni" }}
  connect_address: {{ env "NOMAD_ADDR_patroni" }}

etcd:
  hosts: 10.10.10.10:2379,10.10.10.12:2379,10.10.10.13:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      pg_hba:
      - host all all 0.0.0.0/0 md5
      - host replication replicator 0.0.0.0/0 md5
      - local all postgres peer

  initdb:
  - encoding: UTF8
  - data-checksums

  users:
    postgres:
      password: the-postgres-pass
      options:
      - superuser
      - createrole
      - createdb
      - replication

postgresql:
  listen: 0.0.0.0:{{ env "NOMAD_PORT_postgres" }}
  connect_address: {{ env "NOMAD_ADDR_postgres" }}

  data_dir: /home/patroni/data
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: the-replicator-pass
    superuser:
      username: postgres
      password: the-postgres-pass
    rewind:
      username: rewind
      password: the-rewind-pass

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
