cron: 0 5 * * *
source:
    #enc!
    github:
        - token: ENC[AES256_GCM,data:SXLkT1ZChJsBQAJfK6RFe3mBcvhE/YO95/L1oIqRJf5NRNNez8Fztw==,iv:mAOCXPcTwkDEXsQgtytoSKkKH6Fai2ZbqV7+eDVHiSI=,tag:z7HE0QozMezSFbcepwOygQ==,type:str]
          ssh: ENC[AES256_GCM,data:iS8Kx2Y=,iv:Jonm3t65tM07wBhEWrn4sL6zfcwshxZD5B6IhOTZe3w=,tag:o2PDSubK/dgo/Ef3N5tKfQ==,type:bool]
          sshkey: ENC[AES256_GCM,data:lVp1QZM+1Nkrg636,iv:mK9mblR49AyfIiTG74H5v25Vcg8TMbOX/y38z09L+bQ=,tag:L79UxSz7/wNlFMMzTEmnig==,type:str]
          wiki: ENC[AES256_GCM,data:jt07rg==,iv:y0srtM7u5abt/EpExZ0DZO2Yg1MmXUVFeLUyZJ+eCR8=,tag:6NwLPi6lYSvqgIAi1S1oYA==,type:bool]
          starred: ENC[AES256_GCM,data:/XbzqEU=,iv:GlLVGuFa02XVUljrXHfQVu0sKGAiAx9QlH5+uIjSp2E=,tag:nvZ+tChtqWjnyxhlQO/N4A==,type:bool]
          issues: ENC[AES256_GCM,data:RZw2Kw==,iv:U8xJOtcAAEXW3j1qn/2ChYdgx3w9XW/h4grovVWp5yE=,tag:n/7aDtF3CNAR5/zSJXirKg==,type:bool]
          exclude:
            - ENC[AES256_GCM,data:BXi4Qi2U05fL9/U=,iv:NtQJ/jQUfohmL10LXSFEV67d5nZoMMGMeZKAqPBm3Zw=,tag:q42gDtUWUwISqe5o8RM/Ow==,type:str]
            - ENC[AES256_GCM,data:kPFLK22nz6DI,iv:BeRef3g0CJJaF8gudqdWaMEc4127OBzypBdV5m3ZsW0=,tag:U4yv+9OXJmbkXPZzy2blXw==,type:str]
destination:
    #enc!
    gitea:
        - token: ENC[AES256_GCM,data:+pGkFk4s/8tT0lfMrOagMAnmzFuEEHmHEvTkLWtrGcoD8Mzj62furw==,iv:vaH5sjujutx+/LB1AMTElPqn0gpRdMSsllhjUlTtxc8=,tag:tb6l9CfmxMc4CqjcWa3ncA==,type:str]
          user: ENC[AES256_GCM,data:0g==,iv:VWZ6cQv83HdVxSp9qwgPRMhUVb3rlNn+r4t2FRlbelA=,tag:og+IA9HUk4AN06uMuk4ySQ==,type:str]
          url: ENC[AES256_GCM,data:O7oy799LkFEOjGxi69xlMPr7EqnjJg==,iv:PPDYk7h1F6Ns4/uo1bmRuNQ/G/aLjH5axAWJPibAgDQ=,tag:XvjUVaG/WY8u4zjGxPExlw==,type:str]
          createorg: ENC[AES256_GCM,data:lNWGvtk=,iv:5zHe2oLL6iEcuQwLdipC6MTschC5RxrmiTYt9UE5Imc=,tag:VNqJDosq2fkCHpGHJi2rrQ==,type:bool]
          lfs: ENC[AES256_GCM,data:f2WUWJU=,iv:GOolQi7EKK6yx1DizYhrxmngyCnPinO46uDFMGjX188=,tag:g9d1cI6iicuBe1LwA/8IXA==,type:bool]
          mirror:
            mirrorinterval: ENC[AES256_GCM,data:joA=,iv:AScAIA9fTkicCMP4blw2ENdHrl4qzXFyyHj5nzwOZz4=,tag:ZeLj4QAumuTNHy0Wmahizw==,type:str]
            enabled: ENC[AES256_GCM,data:lpTC0w==,iv:Jv21eW/PN7PL2h2RUpMsmChOs1tQzQuu5FfHNAjPfJA=,tag:HzVBeSL0hgEkNkwSMzpCbQ==,type:bool]
          visibility:
            repositories: ENC[AES256_GCM,data:i9mNHnKT,iv:A73HR/8BYRb0KBWx7c4Bb80x2Bzhz6P37i1ytBHzD3I=,tag:z9SXYQ1NZV3SIKadwMXsag==,type:str]
            organizations: ENC[AES256_GCM,data:T6yCAb5Gxw==,iv:DNkt2AxvxV3MiYpX28gpz3cx7D/CHGqlZu0vimqxYiY=,tag:onYMcnK4pHID2OVf0i1Hwg==,type:str]
          force: ENC[AES256_GCM,data:edZkeuE=,iv:IjrIvMnCDm54oaXolzWo7BndF/nHso1AslHpLwxdfLo=,tag:wQz90DM6s/6SPF/+7VLJvg==,type:bool]
sops:
    age:
        - recipient: age14nu42yf645xewsdgq03rwytpxw4pf6elmlwz9q3yundv32h8l3xqvq7hvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOHM5anRLRjlFZjFGRVlT
            eTlKemk2MEFtcTY4cU5uSTNsSXNTNjdNZndZCkUzcjA3UVVCRHFVUVVLZnpLT0Rn
            RldPcHM5OEhWbHVEVVVKMk4vTlpRbFkKLS0tIDZGSFZyVWduV1FFcHpkaldvcEtX
            aVpBczhiMmZmaHA5dGliWnhVZ0VqU1UKq6RGlGZ69bh21ImIz71rczddpLUR5YLG
            xJRXS40lzmzJuRlKYtyx+ur8FaMQ29Wj8tRs4pLyP1aP/TNYuMnUaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-14T08:25:17Z"
    mac: ENC[AES256_GCM,data:UkpGII+zdyTaj+o8fjs0sPHkKg1KiuQU+covD3ChYAy1hJdklzg07oShFfNn5Vc0UMMXPdoUdQGlZbi3GiM4E4zoLLNsW8mMOSxhusW+FdUHQVdBTgNmguifDcJQ/nvJ7pFr/1JFv60kVcaHHXCWdcATugxoXmKl/OQmnVQNLkU=,iv:36QBGEqOAawTPURAnzLaNNLBtDhcEAsOKDKJz7FG74I=,tag:gL9paA0EU4160uiv6aP17g==,type:str]
    encrypted_comment_regex: enc!
    version: 3.10.1
