cron: 0 5 * * *
source:
    #enc!
    github:
        - token: ENC[AES256_GCM,data:M0NTTdm9VsFpIqd3cXOU+y2uMxpPDZG4Po4Y9ocL1vSZAoVMkq4v6g==,iv:uZsXtypTj4G/O0buTFf/1urR7agFkNUUxREUMxESSJY=,tag:1lNtLi+kYpeDLDxKy+yUQw==,type:str]
          ssh: ENC[AES256_GCM,data:bl4Tudg=,iv:7W8JTqoqY7y6pdZNqCcGcaTiO197YosZ8TXbS2/A1GQ=,tag:QNg9gpatgAdtKv1g4oRCgA==,type:bool]
          sshkey: ENC[AES256_GCM,data:J9AKxtKFITmXLlPs,iv:WOHtDoTGZXL8KkWOJjiSkKhpW/d4muFyGRytb1qOln4=,tag:qSZbLHIibDhtR29S+pwB5Q==,type:str]
          wiki: ENC[AES256_GCM,data:biwjWQ==,iv:iC8d73449VWNvEyU7mNaAezPg2CKf5KdfNNlrfBDsds=,tag:ddurg0clE/rD5Ftdr8Y7vA==,type:bool]
          starred: ENC[AES256_GCM,data:69Gsdc0=,iv:MtO+PIAuRtwpEQV+QfQ5Im0stCY0hOvFPIZKWpawqt8=,tag:Iq8ztgeJ+b0g0W9A/VUeTw==,type:bool]
          issues: ENC[AES256_GCM,data:uSTiUA==,iv:Z7IqD2rIoTNHOULoH8CiqTuJ894gzXqGruiKGVd3PrA=,tag:BXKtDnT4l2L1O73tKjP+TQ==,type:bool]
          exclude:
            - ENC[AES256_GCM,data:bDMXljjyG8fLJ/k=,iv:cS8BFGUflc0swtm11xftl6VIthzf0gcQBs/JvNogRvg=,tag:BXA20ErmSI8LsnxusSrSkg==,type:str]
            - ENC[AES256_GCM,data:xyB8rtzvHa8u,iv:HVrmSJxyHhkemYVjgHh1kvE7q9I8WFAf4hizQSFvRM8=,tag:rGFOGHNtREwca8yubHRp4g==,type:str]
destination:
    #enc!
    gitea:
        - token: ENC[AES256_GCM,data:/akYh0vf/9a41aYVPhvgC9a6Tg3GFcxO48EQY93EvpXymDFfMAFdag==,iv:gmp8np4mdRF+V5FenLCaxD5gZsvX+Os5blJx0/6MR8g=,tag:6Ml0izwXMcwtp5fMz/1a7w==,type:str]
          user: ENC[AES256_GCM,data:tA==,iv:pE6wx3qtODhSizNtCcw0XUQ5ApiUAb4j2BYOScZ84EQ=,tag:u9vQoiABwLwf0vSNexty/Q==,type:str]
          url: ENC[AES256_GCM,data:qSz8g25TpdoDwhUZLwr0kUE2sxuqaA==,iv:hY8b1dxXtWE7vnskOcyhLcmYYxvuBopk0PwJANvwql0=,tag:K8rqvR54rYuRwCMZIeKQzA==,type:str]
          createorg: ENC[AES256_GCM,data:A+N/S48=,iv:HxPeG3wKLA6Y6wPdQwBfY6JGqf2znShS1a4XPprbu+o=,tag:Lip8ScB0uOELwdfVuHZ1eA==,type:bool]
          lfs: ENC[AES256_GCM,data:txI3psA=,iv:Smn/jUDq0XxJayhtraWFlSd7wuBmjHT0yRrytf/RwYY=,tag:4dwqgU32ehPrsQ1UO/xtmw==,type:bool]
          mirror:
            mirrorinterval: ENC[AES256_GCM,data:u6Y=,iv:l/xK9K+oqfcu1/nfZP7p6oeqd5ytaFm9ue0ccw6KPRQ=,tag:y34dS1JwCqs9teKvnCkz0g==,type:str]
            enabled: ENC[AES256_GCM,data:2RpOow==,iv:a/q2wWYpX8Tn0NAoFcPyvjL3dDCtRippzG/69U1CYsY=,tag:SBuDN8ozBZImjD79E1MHqw==,type:bool]
          visibility:
            repositories: ENC[AES256_GCM,data:+orep/nQ,iv:s90wpXRStEwvmS10xjg82S0bfdAXnbZPfdcB0jCFtH4=,tag:mfIFQdA6WZZUO5d9UKrztw==,type:str]
            organizations: ENC[AES256_GCM,data:YgPwXxrsDA==,iv:hzU9+EyKJoeDFt0iLrAgntpW6HopRk038pOaSeOwpb0=,tag:YRdMfTCyrW7cZ4gpfwSmrg==,type:str]
          force: ENC[AES256_GCM,data:qg078Q==,iv:gAcND0B0azO15HLRgT5rIOVxnVMkWhaYyc9jakDHRD8=,tag:97rTxhXMujCFH4fqxZ37Fg==,type:bool]
        - token: ENC[AES256_GCM,data:CyjABQMa3L1+dylQi0Zy6OShdFNE7r4CFOQQprXuIopH7GKlQ5a1iw==,iv:jQhNohJh+H8JgiIw76JNgZj031hIEA+xEMpGb7+a9UQ=,tag:kDh42ebMopCvWOuC+yS1iA==,type:str]
          user: ENC[AES256_GCM,data:Y/MmIBl9nVDKrcs=,iv:zJxnnlTS6bQCO+iHLTbVvVbxZh8rnM06Yg7p7f0AJTc=,tag:qSM2I5FDI0hAyh9d4YwAUA==,type:str]
          url: ENC[AES256_GCM,data:Kj9pvHpwKTzOEbLaozbmMEsmx5g=,iv:/h4Qgbp+RWcK6CidH0axSLpPsj/ZaWUZ3XIVQzso+Ao=,tag:d+YAgOwNewKXO4yxsWRWiQ==,type:str]
          createorg: ENC[AES256_GCM,data:CXGRhgo=,iv:nbUdL8teFh8IDVV6Z9X2GZrjLaHAju6sbcmBQf0Q26c=,tag:WZdaJ5NQC7zKe0Wkq6/eEg==,type:bool]
          lfs: ENC[AES256_GCM,data:1UNrsTY=,iv:OmHN5yQRz/qWNecVeNxrME29LLnhk4+qf+gxEoqLu28=,tag:qSBrbJoOBvjIX80dcBYURQ==,type:bool]
          mirror:
            mirrorinterval: ENC[AES256_GCM,data:2kc=,iv:WSSpUJRX3VHMh3y1PzHD9AqLtfohgisDDGK0THaIeSU=,tag:O1g7FP4Dhf2e/k5nSfbGHg==,type:str]
            enabled: ENC[AES256_GCM,data:JfFDEA==,iv:sDonft5XHmxjqpPDL6f6oSP6glYoAvgvOOtB6F5mE3k=,tag:XKxwIQmzJE1c/QyFFc01ow==,type:bool]
          visibility:
            repositories: ENC[AES256_GCM,data:5VMqzqlu,iv:ZRKalnyyrzYMBIQubus+qZw4MyMo4kSSd7ZW1hK/4lY=,tag:fHXRVN3hAlVfags+agfnHQ==,type:str]
            organizations: ENC[AES256_GCM,data:aioY1JsccA==,iv:9SRImZsTvbDXAL7U+H8XtiSbR3mmGI1yeSY/QFr+5nw=,tag:DJ9XdTYMgvKWOcdEgjSxlg==,type:str]
          force: ENC[AES256_GCM,data:3PldWQ==,iv:21Z9+sm/2BcmSPumVOrIKkPYEr3/160OeJg0rB4GR6o=,tag:OXp+B9rlwxbgsXpV2/31ew==,type:bool]
sops:
    age:
        - recipient: age14nu42yf645xewsdgq03rwytpxw4pf6elmlwz9q3yundv32h8l3xqvq7hvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSmFhYkI3dG1FR3RJUmxT
            OWFFMzF1N2VCOUhOSkkxMGlUYnQrdkNaU0VzCkJkWW9KdnR0SVkwbkdwL2F5OWF3
            Syt0MThSU0RNOXVHYXQzeTR1ZExvRXcKLS0tIFl2L2JUQldwSmlSZWtHa21hdSty
            VWpYTHZnOENpcXZaay9kMHFUMkpDZjgKf+gyhtoKFojh4uP+iGx7Qezz/56feLcW
            YP/13QQ+wmh37linWSh0pVjpfUsqRlsyuguF9Vd7CV7EeTqgpjBoFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-05T15:16:36Z"
    mac: ENC[AES256_GCM,data:k0YIyP8y/q9HR8mkQpmz46xFk8EtBeZ0dmt0xaleCnKREoDeoLgt/RO+pcG4j5clYpKMGEDtYHhg1dWGRkt0/LzjTtZR9d1i/d9CcpwyQl92qGOH7ZGCRtlwbtImCSpvfDcyNkREnRtInWYnb9pZuwsGOUxj7DEtpcXJzh/zg24=,iv:JnD0Gv1ncPOgW6l1D3PjrJIZbk4gXatqJ7lg1TqQS1o=,tag:PjLMt9xlJ790gvLPXM8P5g==,type:str]
    encrypted_comment_regex: enc!
    version: 3.10.2
