cron: 0 5 * * *
source:
    #enc!
    github:
        - token: ENC[AES256_GCM,data:gHmnYV/UtkzrxBjUxX/U4X25l2rQ7zaej5t5FCn7tXIiTw+1QJKS2g==,iv:sap2crAJL1/7ryzzt5rOnrIing+9HlT+qX1dMZV4nhw=,tag:uutVisGVGpigbMKIj6ndZA==,type:str]
          ssh: ENC[AES256_GCM,data:P18ugwQ=,iv:ciuDGA7KhATCxOvsSBcBXcsG/HwvtTgUgZFHkTJjKUs=,tag:M0XxIUXEEZXq/FE/ghP8xw==,type:bool]
          sshkey: ENC[AES256_GCM,data:vivl/mdiNy/3ePsa,iv:tTYjjjwiSd4RUVsvsZ6dDy0bgUYLKn84YaoN5nSjA2o=,tag:fRcWOA0WitgxYuTJH3MXWQ==,type:str]
          wiki: ENC[AES256_GCM,data:pX6+7g==,iv:viumdT0/i2MHaeWAhGSISne2pVJ/vaJsimtg2r5KA+A=,tag:Hs48Gsh+mX11nYYwe7GIvA==,type:bool]
          starred: ENC[AES256_GCM,data:YmQNCcw=,iv:bZc+3DeWGtNqjGETqjUO07d3pdg0P0p7DAx2lKIhbYE=,tag:PwJSeSFkrIZjE0pHcUC7pg==,type:bool]
          issues: ENC[AES256_GCM,data:NUYaVg==,iv:J6OwBQ338ogJ2ByBRSJClLHG9FHsds7A9TCcC3tUnsU=,tag:E6DtfW9dRXRugdpGXyf3RA==,type:bool]
          exclude:
            - ENC[AES256_GCM,data:/c3nucTBnTnIH+8=,iv:nxGHRnEC5fw+hXOp9PWleOTBjKghFszKu9i/PK/ZGrA=,tag:u+a4ofV5x02LsZjrxiOaqw==,type:str]
            - ENC[AES256_GCM,data:s6fE27mvrff3,iv:nCWIQQns6Nhd3tADhPCDRIyqeMN2j8M/Kh4nK114/EQ=,tag:ZEfnDYWz2773tXPfiITMpw==,type:str]
destination:
    #enc!
    gitea:
        - token: ENC[AES256_GCM,data:BxudgzxAgx/YEyWLla1EdNe6MaOe5c/cZx7cEoMEAgfonJJZmYlmYQ==,iv:Hq9YZYc2gV7TDkvAgdDSRw8ZMX1PISUraoNbiu53mns=,tag:3T+og05zATMMTHathv/UcQ==,type:str]
          user: ENC[AES256_GCM,data:BQ==,iv:NCKZ3QrzfEzAtA0jr5PSjLaz+lJXoj1kDa1sDTGti8c=,tag:bhffcySMb3JyAlStkTQm6Q==,type:str]
          url: ENC[AES256_GCM,data:GrUk7g8Kl9VTdZ0xZFP1pPBycsUR2A==,iv:KOrcRUiQW67mUzzVR/DdbcsnvW0Mf3o+3bLLyKqBraQ=,tag:NlswXT117E6XsHvIT90s2g==,type:str]
          createorg: ENC[AES256_GCM,data:NGooEPk=,iv:iOe9ZVHtFlRHpKpFkIenw7YMUo0Je+VjOXFzw9ExaOU=,tag:pYBo53mTjemD2JhURwMmaQ==,type:bool]
          lfs: ENC[AES256_GCM,data:xUBQdcs=,iv:9CAKZLKHHY6YLyC5nsvNA57A3IC62YqvC2C6vPq+JQY=,tag:DU6HIGhmrR+esyd1SRzZLQ==,type:bool]
          mirror:
            mirrorinterval: ENC[AES256_GCM,data:LJ8=,iv:r8q6iHFnbXVsDWuK0My9bxSC7rrRcxXz09ZsB/nKEkQ=,tag:D/464cWFbJDDm2ABz1VfSg==,type:str]
            enabled: ENC[AES256_GCM,data:eosRtA==,iv:KYYiuxUxcxkzLH1CiOxQbuLdtceRYhp1T6QJW5S3Btw=,tag:ScEcGZHRJTZQ1ObAbx4Psg==,type:bool]
          visibility:
            repositories: ENC[AES256_GCM,data:C2boHdbf,iv:7YI4ecK4qT+xusAz4OIKWVZBXTTagCL1b+6iCiRCK9M=,tag:StQVU9x/H+ud8y0LXYF8ow==,type:str]
            organizations: ENC[AES256_GCM,data:DTpNmD7NhQ==,iv:iWWUULYXNoRrpcYpWX5dC0Ghg3L+Yr6WYmaUliJl+dQ=,tag:U4fI3nLPeHIvIRsmlFGEQQ==,type:str]
          force: ENC[AES256_GCM,data:AftoLA==,iv:xfHIrO6atQH02hLiwG8MVqVLgHhp/+pQgbB6cgqgcII=,tag:DgUBh1MHCSAsNN6a+qXlFQ==,type:bool]
sops:
    age:
        - recipient: age14nu42yf645xewsdgq03rwytpxw4pf6elmlwz9q3yundv32h8l3xqvq7hvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVE0xMkxHSnJ0WHVhcWF6
            dXhONllmZnZDdjVGUkl3UUUvMFdnaDZJcUI0Cnphcmlyd3hWU3dSdEU5bHJFUWZ6
            MmJJSW5paE1GMVg1YTR2VUIyY1lCTjAKLS0tIDF3TC9qSkJZZ2RYTFRTWHVWc2pI
            S1VNNHdDK2NKM3FkVlZUSC9uQUcyNGsKlRZN172Wr4iRHrkM4Kbc0GMmMHkMa/lL
            UMeJMWuuhExzeezJdfHOzU8Er2CyRTPK/m7ggxTEYTuVZD/OGILGbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T08:27:33Z"
    mac: ENC[AES256_GCM,data:OUs6MJooNdd8J1mZkbPk9KmOsRixIku+qiF32Y2G9kV9ifQnDYAQlIha//OQUJ4CKW94RkKNAtjwdx/9tnErWcJ54H5HINr2SIvJYQYg5pljPa7fSlttMnXTy19PIzBdPI9A/YEDgyl4bOUFWRKsHdswbn/6mu1Pg5y80faroxY=,iv:8TxNoosOaDI1M9rVcS5HjIm3ZuLWxr+fSrY4Xj1CtGY=,tag:ki0+yrXgG7cOOTT2VxJA3g==,type:str]
    encrypted_comment_regex: enc!
    version: 3.10.1
