cron: 0 5 * * *
source:
    #enc!
    github:
        - token: ENC[AES256_GCM,data:vusAFS3GlWVOvEfmDQndDJlSSTUVFSwY/YN+29W+oo0z0hYw7O3ZzA==,iv:tfZS/fSlj3dofjnQoFUK/C2KHR8WrC1QMDZVLyG+3Zs=,tag:Swnh22HC5B9gHYYxXDLnew==,type:str]
          ssh: ENC[AES256_GCM,data:T9CcBEg=,iv:iA5g8bdWu3MUS/Q76DoIp60xNqZHzsfd/TT5EEo3ebQ=,tag:yxM/yYR6X1fFSMVN+p5s5g==,type:bool]
          sshkey: ENC[AES256_GCM,data:0eoSDZhZ2ZVe8ad9,iv:wB09xxp3bl+ji7bkN2zsPzovYLoGxuhYxfoYMgn4FaI=,tag:mvQk6rd20WYB3gDASkLNyQ==,type:str]
          wiki: ENC[AES256_GCM,data:Mtr6PQ==,iv:6BLhWAxCfL9IQf9e5K1jrpIxD1wl1govyQtGbgRcOrQ=,tag:vI6A3XvpLx5/4YAeoqaVGA==,type:bool]
          starred: ENC[AES256_GCM,data:c7iSKP4=,iv:egdg/doycNBi80WedPbfQlr38WqXaaQS/6GRqqUbt50=,tag:2k10OySFk+Al+lUIvCVyWA==,type:bool]
          issues: ENC[AES256_GCM,data:b13Hmw==,iv:S4Pq2VFJyytB7WTnASIvAK7Z1DK8rKdTyZcsl7EjZiA=,tag:qW27oATr2kEzWuqhDNYM3g==,type:bool]
          exclude:
            - ENC[AES256_GCM,data:pzKzVGyZe+Jn2nw=,iv:uVzxTPSvsneheilXl8IkmCOElYeRIa38r05HvjUkaAs=,tag:q5/TC19HILNIP/i+hnv1gw==,type:str]
            - ENC[AES256_GCM,data:/6a9TFnQ0Ebo,iv:m6r6xnLv910hYsEhO7KvG/XMAZsbF5Yt1Xu2OTVRR0s=,tag:HeWxvfF77qBnSbUbOcpqDQ==,type:str]
destination:
    #enc!
    gitea:
        - token: ENC[AES256_GCM,data:lxgpa7yBQFEkbObL0HdtgxeGZb4ViMTBKAElDXk3BXytAv4HZNWqnQ==,iv:l9uWWdh6YokqvN2aOw3DoXoP7EZhnD9PxKogcCSrybE=,tag:ikHXribyptIk5as8YaNgWQ==,type:str]
          user: ENC[AES256_GCM,data:Bg==,iv:jygxYMHy8ebr3++EJO0vM/LjqimspKM1nnB2In9UJ4Y=,tag:SOMqnIUdVMZL/ph+7uan2g==,type:str]
          url: ENC[AES256_GCM,data:wTT6qfMG50bsjb4vBdyzu47rohKi8Q==,iv:0bo6EnZp6eRtx9ydxnL8433rymQUy3Ayd2eHv1zODiI=,tag:XBiI/wPkYiGSf9ahAwmbig==,type:str]
          createorg: ENC[AES256_GCM,data:Y7s9mYo=,iv:3LwpR75I/o3LswP/PwcHx+M65C2FSoQAjoXtiZLwMGA=,tag:G/ywpSybIYaE50FGqlSY3A==,type:bool]
          lfs: ENC[AES256_GCM,data:Cw4zXMU=,iv:JQ2Oyy/0X+dn4EKBull1cAhDvV6PH/PSpfk+p6Z/Y5w=,tag:0TaIBAEdfw8UExWuE8wEqw==,type:bool]
          mirror:
            mirrorinterval: ENC[AES256_GCM,data:K2g=,iv:SFFYxgVLtAx4n8K+CtjfYpasL15j6e64T1IL89zSJkQ=,tag:NYE7ZnJ//IkbbKP+FYuukw==,type:str]
            enabled: ENC[AES256_GCM,data:CPdO1nc=,iv:gSqwCsieehiLaj91sE1HE314nQVwW/Dui+Hwx+ugPag=,tag:boFMAGpNFdDOzuduao03cQ==,type:bool]
          visibility:
            repositories: ENC[AES256_GCM,data:hZmLp8h5,iv:dJ3DGW+bG+7JPp7+SQ5RWZ6++QkpNjZDuTt136MQ+Fs=,tag:WWv1wrfA75XGmRS6zxUHow==,type:str]
            organizations: ENC[AES256_GCM,data:pOMDNkkzCg==,iv:k7rWQU9xAgofMgIBU9vsdTLRjhIALPCWnb2LiMreSRM=,tag:vNCBCwB5Vufd/nzXG/i95g==,type:str]
          force: ENC[AES256_GCM,data:ixERrQ==,iv:CdXUhiXitB5RydHcOaGMatfp+OzA3P9EewaJKSYY4ZY=,tag:kNfKIZ6/+usNTSuwpEsjag==,type:bool]
sops:
    age:
        - recipient: age14nu42yf645xewsdgq03rwytpxw4pf6elmlwz9q3yundv32h8l3xqvq7hvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVDJCdS8xVUFFQmY4bjBD
            ZkU4VEwwSEYyT0dmUkFrZVlReU5KNm1CQWdZCk1jMi9zWDhrQ2daLzN3YjJkQnlW
            bWRMNGt2c3J5MjBnZnNlRERuODVaSkEKLS0tIHhMT05VTXdDb3ZyT25wQ0pFbkhv
            RUIrUVJPcmlIQ09MNURlR1hYekt5Mk0KCzV5hyfPxI727ET8jhskPCHLI2WHtYVg
            R+mV2tpYGDoH17mep8V7fLnqu+g9CUnhW1mzNgNYJ6RG0106Pl6AzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T08:09:39Z"
    mac: ENC[AES256_GCM,data:9EQfWHlIhRApx+PizROkIe5Mijes2ZBmKd70CeqFC3CJ+NN7wEyALlmoJP2JXm542HWd1YpJA5a1myhq02ImJzclJiyboTL1SyDt7424AwR7RZlIW/GQAjZ4yyw6laEfsdT543s+VO0gZKwoXOY1O8wQYNcIrBM/468nFiAmCxs=,iv:ppMdtFKDULuN079/IlcNpQXgVM4Z7Y8R4nq4Nsk3RS4=,tag:YC6MY2a2Us2l+ExmM8Q96g==,type:str]
    encrypted_comment_regex: enc!
    version: 3.10.1
